apiVersion: v1
kind: ConfigMap
metadata:
  name: vrp-config
  namespace: vrp-demo
  labels:
    app.kubernetes.io/part-of: vrp-demo
data:
  MERCHANT_SVC_ADDR: "merchant-svc:50051"
  CONSENT_SVC_ADDR: "consent-svc:50052"
  PAYMENT_SVC_ADDR: "payment-svc:50053"
  RISK_SVC_ADDR: "risk-svc:50054"
  LEDGER_SVC_ADDR: "ledger-svc:50055"
  BANK_ADAPTER_ADDR: "bank-adapter:50056"
  MERCHANT_GRPC_ADDR: ":50051"
  CONSENT_GRPC_ADDR: ":50052"
  PAYMENT_GRPC_ADDR: ":50053"
  RISK_GRPC_ADDR: ":50054"
  LEDGER_GRPC_ADDR: ":50055"
  BANK_GRPC_ADDR: ":50056"
  MOCK_BANK_HTTP_ADDR: ":18080"
  BANK_HTTP_BASE_URL: "http://bank-adapter:8080"
  GATEWAY_HTTP_ADDR: ":8080"
  REDIS_ADDR: "redis:6379"
  KAFKA_BROKERS: "redpanda:9092"
  LOG_LEVEL: "info"
  ENVIRONMENT: "kind"
  PAYMENT_SAGA_TIMEOUT: "10s"
  WEBHOOK_RETRY_MAX: "6"
  CONSENT_CACHE_TTL: "300s"
  RATE_LIMIT_RPS: "100"
  MOCK_BANK_FAIL_RATE: "0"
  JWT_TTL: "1h"
